baseurl = "https://ewen.io/"
title = "ewen"
languageCode = "en"
theme = "kiss"
copyright = "&copy; Ewen Henderson </a> 2017-18"

Paginate = 5
enableRobotsTXT = true

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "ewen" # Title for home page
poweredby = false # Adds powered by Hugo and Kiss below Copyright section
related = false # Includes related articles

[params.social]
email = "ewenhenderson@gmail.com"
twitter = "ewen_"
github = "ewenme"

[taxonomies]
tag = "tags"

[permalinks]
blog = "/:year/:month/:day/:slug/"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
