theme = "hugo-theme-codex"

baseURL = "https://ewen.io/"
title = "ewen"
description = "ewen's writing and projects."
languageCode = "en"
copyright = "© {year}"

enableEmoji = true
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[author]
  name = "ewen"
  email = "ewenhenderson@gmail.com"

[params]
  dateFormat = "2 Jan, 2006"
  email = "mailto:ewenhenderson@gmail.com"
  twitter = "https://twitter.com/ewen_"
  github = "https://github.com/ewenme"
  iconTitles = ["Email", "Twitter", "GitHub"]

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

[permalinks]
blog = "/:year/:month/:day/:slug/"
