baseurl = "https://ewenme.rbind.io/"
title = "ewenme"

theme = "minimo"

disqusShortname = "http-ewenme-rbind-io"
googleAnalytics = "UA-98719738-1"

Paginate = 8

preserveTaxonomyNames = false

[params]
  fontbody = "Work Sans"
  fontheading = "Open Sans"
  favicon = "favicon.ico"
  customCSS = ["css/custom.css"]
  CopyrightOwner = "Ewen Henderson"
  CopyrightStartYear = "2017"
  dateFormat = "02 Jan, 2006"
  listDateFormat = "02 Jan, 2006"
  hideEntryNavigation = true
  hideSocialMenu = false
  showReadTime = true
  

[taxonomies]
  tag = "tags"

[author.social]
  email = "ewenhenderson@gmail.com"
  github = "ewenme"
  twitter = "ewen_"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "home"
  weight = -80
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "blog"
  weight = -70
  identifier = "blog"
  url = "/blog"

defaultContentLanguage = "en"

[languages]
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
