baseurl = "https://ewenme.rbind.io/"
title = "ewenme"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
pluralizeListTitles = false
# Enable comments by entering your Disqus shortname
disqusShortname = "http-ewenme-rbind-io"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-98719738-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = ""
  copyright = "&copy;2017 Ewen Henderson"
  sidebarAbout = [
    "<big><i>Pronounced you-n-me</i></big> <br> <br> Opinionated analysis, adventures in R and humane, ethical applications of machine learning"
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "Blog"
  url = "blog/"

  [[params.navlinks]]
  name = "Projects"
  url = "projects/"

  [[params.navlinks]]
  name = "About"
  url = "about/"


  [params.social]
  email        = "ewenhenderson@gmail.com"
  twitter      = "https://twitter.com/ewen_"
  github       = "https://www.github.com/ewenme"

  #Adding widgets to the sidebar
  [params.widgets]
    categories = false
    tags = false
    search = false
