baseurl = "https://ewenme.rbind.io/"
title = ""
theme = "tuftesque"
publishDir = "public"
languageCode = "en-us"
pluralizeListTitles = false
disqusShortname = "http-ewenme-rbind-io"
googleAnalytics = "UA-98719738-1"
author = "Ewen Henderson"   

  [permalinks]
    post = "/:year/:month/:day/:slug/"

  [[menu.main]]
  name = "About"
  url = "about/"

  [[menu.main]]
  name = "Blog"
  url = "blog/"

  [[menu.main]]
  name = "Projects"
  url = "projects/"

  [[menu.main]]
    name = "@ewen_"
    url = "https://twitter.com/ewen_"

  [[menu.main]]
    name = "@ewen_"
    url = "https://twitter.com/ewen_"

  [[menu.main]]
    name = "GitHub"
    url = "https://www.github.com/ewenme"

  [[menu.main]]
    name = "Mail"
    url = "ewenhenderson@gmail.com"

[params]
  description = "<big><i>Pronounced you-n-me</i></big>. Opinionated analysis, adventures in R and humane, ethical applications of data science"

  showtitle = false
  [params.logo]
    url = "/images/logo.png"
    width = 50
    height = 50
    alt = "Logo"
