baseurl = "https://ewen.io/"
title = "ewen"
languageCode = "en"
theme = "kiss"
copyright = ""
Paginate = 5
enableRobotsTXT = true
description = "ewen's blog and assorted projects."

[params.rss]
includeContent = true
authorName = "ewen"
authorEmail = "ewenhenderson@gmail.com"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
description = "ewen's blog and assorted projects."
enableSocial = true
homeTitle = "ewen"
poweredby = false
related = false

[params.social]
email = "ewenhenderson@gmail.com"
twitter = "ewen_"
github = "ewenme"
rss = "index.xml"

[taxonomies]
tag = "tags"

[permalinks]
blog = "/:year/:month/:day/:slug/"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
