theme = "lines"
baseURL = "https://ewen.io/"
title = "ewen"
languageCode = "en"
paginate = 999
minify = true
enableEmoji = true
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[taxonomies]
  tag = "tags"
  
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[Author]
  name = "ewen"
  email = "ewenme@tutanota.com"

[params]
  description = "ewen's writing and projects."
  author = "ewen"

[permalinks]
  posts = "/:year/:month/:day/:slug"
  pages = "/:slug"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "index"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "index"
    name       = "index"
    url        = "/"
    weight     = -111
    
  [[menu.main]]
    identifier = "contact"
    name       = "contact"
    url        = "mailto:ewenme@tutanota.com"
    weight     = -20

  [[menu.main]]
    identifier = "rss"
    name       = "RSS"
    url        = "/index.xml"
    weight     = -10
