theme = "hugo-theme-codex"

baseURL = "https://ewen.io/"
title = "ewen"
description = "ewen's writing and projects."
languageCode = "en"
copyright = "© {year}"

enableEmoji = true
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  dateFormat = "Jan 2 2006"
  email = "mailto:ewenhenderson@gmail.com"
  twitter = "https://twitter.com/ewen_"
  github = "https://github.com/ewenme"
  iconTitles = ["Email", "Twitter", "GitHub"]

[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

[permalinks]
blog = "/:year/:month/:day/:slug/"
